version: "3"
services:
  mongodb:
    container_name: mongo-db
    image: mongo:5.0.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=ggxxreload
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./docker-entrypoint-initdb.d/.


