server:
  address: localhost
  port: 80
  servlet:
    context-path: /ggxxreload

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
     # uri: ${MONGODB_URI} for hosting
logging:
  level:
    web: INFO

deactivate:
  time:
    delay: 180
    schedule: 30