server:
  address: localhost
  port: 80
  servlet:
    context-path: /ggxxreload

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
     # uri: ${MONGODB_URI} for hosting
logging:
  level:
    web: INFO

schedule:
  afk-players:
    delay: 180
    frequency: 30
  ping-players:
    frequency: 2
    timeout: 5000


deactivate:
  time:
    delay: 180
    schedule: 30